"""
Render the LangGraph agent graph as Mermaid — the single source of truth is the compiled
`StateGraph` itself, so the diagram can never drift from the code.

    # print Mermaid to stdout
    python -m app.scripts.draw_graph

    # rewrite the diagram block inside AI_FEATURES.md in place
    python -m app.scripts.draw_graph --write

    # exit 1 if AI_FEATURES.md is out of date (CI guard)
    python -m app.scripts.draw_graph --check

No DB connection or OPENAI_API_KEY is made — building the graph only wires node functions; the
LLM is called lazily at runtime. Config import still needs DATABASE_URL + SECRET_KEY in the env
(any values), e.g. `DATABASE_URL=postgresql://x SECRET_KEY=x python -m app.scripts.draw_graph`.
"""
import sys
from pathlib import Path

from app.modules.agent.graph import get_graph

DOC = Path(__file__).resolve().parents[2] / "AI_FEATURES.md"
BEGIN = "<!-- BEGIN:agent-graph"
END = "<!-- END:agent-graph -->"


def mermaid() -> str:
    return get_graph().get_graph().draw_mermaid().strip()


def _block() -> str:
    note = "generated by `python -m app.scripts.draw_graph --write`; do not edit by hand"
    return f"{BEGIN} — {note} -->\n```mermaid\n{mermaid()}\n```\n{END}"


def _splice(text: str) -> str:
    start, end = text.index(BEGIN), text.index(END) + len(END)
    return text[:start] + _block() + text[end:]


def main() -> None:
    arg = sys.argv[1] if len(sys.argv) > 1 else ""
    if arg == "--write":
        DOC.write_text(_splice(DOC.read_text()))
        print(f"updated {DOC.name}")
    elif arg == "--check":
        current = DOC.read_text()
        if _splice(current) != current:
            sys.exit(f"{DOC.name} is stale — run: python -m app.scripts.draw_graph --write")
        print(f"{DOC.name} is up to date")
    else:
        print(mermaid())


if __name__ == "__main__":
    main()
