"""
Render the LangGraph agent graph as Mermaid — the single source of truth is the compiled
`StateGraph` itself, so the diagram can never drift from the code.

    # print Mermaid to stdout
    python -m app.scripts.draw_graph

    # rewrite the diagram block in README.md and backend/AI_FEATURES.md in place
    python -m app.scripts.draw_graph --write

    # exit 1 if either doc is out of date (CI guard)
    python -m app.scripts.draw_graph --check

No DB connection or OPENAI_API_KEY is made — building the graph only wires node functions; the
LLM is called lazily at runtime. Config import still needs DATABASE_URL + SECRET_KEY in the env
(any values), e.g. `DATABASE_URL=postgresql://x SECRET_KEY=x python -m app.scripts.draw_graph`.
"""
import sys
from pathlib import Path

from app.modules.agent.graph import get_graph

ROOT = Path(__file__).resolve().parents[3]
DOCS = [ROOT / "README.md", ROOT / "backend" / "AI_FEATURES.md"]
BEGIN = "<!-- BEGIN:agent-graph"
END = "<!-- END:agent-graph -->"


def mermaid() -> str:
    return get_graph().get_graph().draw_mermaid().strip()


def _block() -> str:
    note = "generated by `python -m app.scripts.draw_graph --write`; do not edit by hand"
    return f"{BEGIN} — {note} -->\n```mermaid\n{mermaid()}\n```\n{END}"


def _splice(text: str) -> str:
    start, end = text.index(BEGIN), text.index(END) + len(END)
    return text[:start] + _block() + text[end:]


def main() -> None:
    arg = sys.argv[1] if len(sys.argv) > 1 else ""
    if arg == "--check":
        stale = [d.name for d in DOCS if _splice(d.read_text()) != d.read_text()]
        if stale:
            sys.exit(f"stale: {', '.join(stale)} — run: python -m app.scripts.draw_graph --write")
        print(f"up to date: {', '.join(d.name for d in DOCS)}")
    elif arg == "--write":
        for d in DOCS:
            d.write_text(_splice(d.read_text()))
        print(f"updated: {', '.join(d.name for d in DOCS)}")
    else:
        print(mermaid())


if __name__ == "__main__":
    main()
