import {
  amountRemaining,
  isOverdue,
  progressPercentage,
  totalWithInterest,
} from './debt-computed';

// Every expectation below was generated by running the pydantic computed_field expressions under
// CPython, not derived by hand — the scales are too surprising to guess.
describe('progressPercentage — min((paid / amount) * 100, 100)', () => {
  it.each([
    ['50.00', '50.00', '100'],
    ['300.00', '100.00', '33.33333333333333333333333333'],
    ['200.00', '50.00', '25.00'],
    ['100.00', '150.00', '100'],
    ['100.00', '0.00', '0'],
    ['1000.00', '333.33', '33.33300'],
    ['7.00', '1.00', '14.28571428571428571428571429'],
  ])('amount %s paid %s -> %s', (amount, paid, expected) => {
    expect(progressPercentage(amount, paid)).toBe(expected);
  });

  it('answers a bare "0" for a non-positive amount, short-circuiting the division', () => {
    expect(progressPercentage('0.00', '10.00')).toBe('0');
  });
});

describe('amountRemaining — max(amount - paid, 0)', () => {
  it('keeps the subtraction scale when the debt is settled exactly', () => {
    expect(amountRemaining('50.00', '50.00')).toBe('0.00');
  });

  it('collapses to the literal zero when overpaid, dropping the scale', () => {
    expect(amountRemaining('100.00', '150.00')).toBe('0');
  });

  it('subtracts normally otherwise', () => {
    expect(amountRemaining('300.00', '100.00')).toBe('200.00');
    expect(amountRemaining('1000.00', '333.33')).toBe('666.67');
  });
});

describe('totalWithInterest', () => {
  it('adds accrued interest at the larger scale', () => {
    expect(totalWithInterest('100.00', '5.50')).toBe('105.50');
    expect(totalWithInterest('100.00', '0.00')).toBe('100.00');
  });
});

describe('isOverdue', () => {
  const now = '2026-08-11 12:00:00.000000';

  it('is false when paid, whatever the due date', () => {
    expect(isOverdue(true, '2020-01-01 00:00:00', now)).toBe(false);
  });

  it('is false without a due date', () => {
    expect(isOverdue(false, null, now)).toBe(false);
  });

  it('compares naive strings correctly across differing fractional precision', () => {
    expect(isOverdue(false, '2026-08-11 11:59:59', now)).toBe(true);
    expect(isOverdue(false, '2026-08-11 12:00:00.000001', now)).toBe(false);
    expect(isOverdue(false, '2026-12-01 00:00:00', now)).toBe(false);
  });
});
