import { randomUUID } from 'node:crypto';
import {
  BeforeInsert,
  BeforeUpdate,
  Column,
  DeleteDateColumn,
  PrimaryColumn,
} from 'typeorm';

/**
 * Mirrors backend/app/models/base.py: id, created_at, updated_at, deleted_at (soft delete).
 *
 * id/created_at/updated_at have no database-level defaults — Alembic never added them,
 * since the FastAPI SQLAlchemy models generate all three client-side
 * (`default=uuid.uuid4` / `default=utcnow` / `onupdate=utcnow`). `createdAt`/`updatedAt`
 * are therefore plain columns generated by the hooks below rather than
 * `@CreateDateColumn`/`@UpdateDateColumn`, which assume the DB fills in a value when the
 * property is left undefined — here that resolves to a literal SQL `DEFAULT` with no
 * matching column default, which Postgres rejects with a NOT NULL violation. Explicit
 * hooks make generation deterministic and mirror how `generateId()` already handles `id`.
 *
 * IMPORTANT: these hooks only run via `repository.save()`. Bulk `insert()`/`update()`/
 * `delete()`/`upsert()` (including their QueryBuilder equivalents) skip entity listeners
 * entirely and will leave id/created_at/updated_at null — always write through `save()`.
 * (`upsert()` is worth calling out explicitly: it's the natural-looking choice for syncing
 * a user from an OAuth provider, and it fails the same way `insert()` does.)
 *
 * `softRemove()`/`recover()` are a save()-adjacent exception: they fire dedicated
 * soft-remove/recover events rather than before-update, so they write `deleted_at` directly
 * without bumping `updatedAt` — unlike a manual `user.deletedAt = new Date(); save(user)`,
 * which does bump it. Harmless here since it happens to match FastAPI's own `soft_delete()`
 * (which also only touches `deleted_at`), but it's accidental, not designed.
 */
export abstract class BaseModel {
  @PrimaryColumn('uuid')
  id!: string;

  @Column({ type: 'timestamptz' })
  createdAt!: Date;

  @Column({ type: 'timestamptz' })
  updatedAt!: Date;

  @DeleteDateColumn({ type: 'timestamptz' })
  deletedAt!: Date | null;

  @BeforeInsert()
  generateId(): void {
    if (!this.id) this.id = randomUUID();
  }

  @BeforeInsert()
  setTimestampsOnInsert(): void {
    const now = new Date();
    this.createdAt = now;
    this.updatedAt = now;
  }

  @BeforeUpdate()
  setUpdatedAtOnUpdate(): void {
    this.updatedAt = new Date();
  }
}
